name: children_games
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  maze: ^3.0.0
  audioplayers: ^5.2.1
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  flutter_bloc_list_manager: ^0.5.1
  get: ^4.6.6
  confetti: ^0.7.0
  image: ^4.1.4


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets\fonts\Cairo-Black.ttf

    - family: CairoBold
      fonts:
        - asset: assets\fonts\Cairo-Bold.ttf   
          